### ISSUE TITLE
System Notifications not working for "NSWindowDidMoveNotification"

### ISSUE THREAD

**Issue by swalker326** [ahkohd/tauri-toolkit#120]
Maybe I misunderstand the use case but when I move a window, I would expect to see a log:

```rust
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            #[cfg(all(desktop))]
            app.handle()
                .listen_workspace("NSWindowDidMoveNotification", |app_handle| {
                    println!("The window moved!");
                });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

Are there some notifications this just doesn't work with?

**Comment by ahkohd** [comment]
Yes, you cannot use this notification as you're not the main actor.

See what the docs says:
https://developer.apple.com/documentation/appkit/nswindowdidmovenotification
<img width="981" alt="image" src="https://github.com/user-attachments/assets/da4aece8-7fdf-4489-b1df-4edb34325ae8">

unlike `NSWorkspaceActiveSpaceDidChangeNotification` which the system posts this notification on an arbitrary actor.
https://developer.apple.com/documentation/appkit/nsworkspaceactivespacedidchangenotification
<img width="981" alt="image" src="https://github.com/user-attachments/assets/9765a18b-342f-4ab1-bc53-f21184e5873d">


To detect when a window moves, you can easily use the accessibility APIs. Another method is to get the list of windows on the screen every X seconds and compare their positions to identify changes.
